env:
  browser: true
  es2021: true
  jest: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules: {
  'no-console': 'off',
  'react/jsx-filename-extension': [1, { "extensions": [".js", ".jsx"] }],
  'no-underscore-dangle': 'off',
  'react/no-array-index-key': 'off'
}
