const constants = {
  NEW_INVENTORY_ARRIVED: 'NEW_INVENTORY_ARRIVED',
  ADD_INVENTORY: 'ADD_INVENTORY',
  UPDATE_INVENTORY: 'UPDATE_INVENTORY',
  TOGGLE_SUGGESTION: 'TOGGLE_SUGGESTION',
  CHECK_TRANSFER: 'CHECK_TRANSFER',
  SUGGEST_TRANSFER: 'SUGGEST_TRANSFER',
  CONFIRM_INVENTORY_TRANSFER: 'CONFIRM_INVENTORY_TRANSFER',
  RESET_TRANSFER: 'RESET_TRANSFER',
  UPDATE_ALERT: 'UPDATE_ALERT',
  UPDATE_QUERY: 'UPDATE_QUERY',
  UPDATE_TIMESTAMP: 'UPDATE_TIMESTAMP',
};

export default constants;
